# Docker Compose configuration for Digital Ocean Droplet
version: '3.8'
services:
  main-app:  # Your existing service
    image: stephengpope/no-code-architects-toolkit:latest
    ports:
      - "8080:8080"  # Maps host port 8080 to container port 8080
    restart: always
    # Add other configs if needed (volumes, etc)

  n8n:  # New service
    image: n8nio/n8n
    ports:
      - "5678:5678"  # Maps host port 5678 to container port 5678
    restart: always
    environment:
      - N8N_PORT=5678
      - N8N_HOST=0.0.0.0
      # Authentication (MUST set these in Digital Ocean environment variables)      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secure_password_here
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:  # Persistent storage for workflows