FROM n8nio/n8n

# Expose default n8n port
EXPOSE 5678

ENV N8N_PORT=5678
ENV N8N_HOST=0.0.0.0
ENV N8N_BASIC_AUTH_ACTIVE=true

# The credentials will be provided via environment variables
# CMD will be inherited from the base image
